apiVersion: consul.hashicorp.com/v1alpha1
kind: IngressGateway
metadata:
  name: ingress-gateway
  namespace: consul
spec:
  listeners:
    - port: 8080
      protocol: http
      services:
        - name: frontend
          hosts: ["bird.localhost"]
        - name: guy
          hosts: ["guy.localhost"]
        - name: external-vault
          hosts: ["vault.localhost"]    